[tool.poetry]
name = "demo-plugin"
version = "0.1.0"
description = "Demo plugin"
packages = [{include = "demo_plugin"}]

[tool.poetry.scripts]
demo-plugin = "demo_plugin.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
